<a href="https://colab.research.google.com/github/Mori-Don/RabbitChallenge/blob/main/RabbitChallenge_PythonKoza_11_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # PY11

In [1]:
#numpy
import numpy as np

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [6]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [7]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
np.random.random((3, 4))

array([[0.83874993, 0.22816351, 0.4481481 , 0.83672387],
       [0.24266516, 0.45218017, 0.44041978, 0.75264383],
       [0.86665477, 0.64507613, 0.53944797, 0.25373545]])

In [9]:
np.random.normal(0, 1, (3,3))

array([[ 0.37930683,  0.15835296, -0.08344025],
       [ 0.12637736,  0.84736737, -0.65100987],
       [ 0.38174702,  0.12719982,  2.23809916]])

In [10]:
np.random.randint(0, 255, (100,150))

array([[159, 108,  10, ..., 102,  75,  49],
       [209,  63,  28, ...,  90,  24,  75],
       [ 74,  66, 101, ..., 175, 124,   4],
       ...,
       [ 11, 115,  58, ...,  44,  11,  89],
       [ 73, 178,  12, ..., 234, 167,   6],
       [ 54,  93,  22, ..., 231, 103,  70]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#PY12

In [12]:
from sklearn import datasets

mnist = datasets.load_digits()

In [13]:
mnist["images"]

array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  0.,  0.],
        [ 0.,  0.,  8., ..., 16.,  0.,  0.],
        ...,
        [ 0.,  9., 16., ...,  0.,  0.,  0.],
        [ 0.,  3., 13., ..., 11.,  5.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

       ...,

       [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ...,  2.,  1.,  0.],
        [ 0.,  0., 16., ..., 16.,  5.,  0.

In [14]:
mnist["target"]

array([0, 1, 2, ..., 8, 9, 8])

In [15]:
mnist["images"].ndim

3

In [16]:
mnist["target"].ndim

1

In [17]:
mnist["images"].shape

(1797, 8, 8)

In [18]:
mnist["target"].shape

(1797,)

In [19]:
x1 = np.zeros(6, dtype=np.float16)
x2 = np.zeros((3, 4), dtype=np.uint8)
x3 = np.zeros((3, 4, 5), dtype=np.float32)

In [20]:
x1

array([0., 0., 0., 0., 0., 0.], dtype=float16)

In [21]:
x2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [22]:
x3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)

In [23]:
x1.ndim

1

In [24]:
x2.ndim

2

In [25]:
x3.ndim

3

In [26]:
x1.shape

(6,)

In [27]:
x2.shape

(3, 4)

In [28]:
x3.shape

(3, 4, 5)

In [29]:
x1.size

6

In [30]:
x2.size

12

In [31]:
x3.size

60

In [32]:
x1.dtype

dtype('float16')

In [33]:
x2.dtype

dtype('uint8')

In [34]:
x3.dtype

dtype('float32')

#PY13

In [35]:
#一次元
x1 = np.random.randint(10, size=(6))
x1

array([3, 1, 0, 7, 8, 0])

In [36]:
x1[0]

3

In [37]:
x1[3]

7

In [38]:
x1[-1]

0

In [39]:
x1[-4]

0

In [40]:
x1[2] = 8
x1

array([3, 1, 8, 7, 8, 0])

In [41]:
#多次元
x2 = np.random.randint(10, size=(3,4))
x2

array([[1, 2, 7, 1],
       [7, 5, 1, 8],
       [2, 2, 3, 3]])

In [42]:
x2[0, 0]

1

In [43]:
x2[2, -1]

3

In [44]:
x2[0, 0] = 12
x2

array([[12,  2,  7,  1],
       [ 7,  5,  1,  8],
       [ 2,  2,  3,  3]])

In [45]:
#ビュー
x3 = np.random.randint(10, size=(3,4))
x3

array([[1, 8, 5, 4],
       [8, 7, 3, 8],
       [4, 0, 2, 7]])

In [46]:
x3_sub = x3[:2, :2]
x3_sub

array([[1, 8],
       [8, 7]])

In [47]:
x3_sub[0, 0] = 99
x3_sub

array([[99,  8],
       [ 8,  7]])

In [48]:
x3

array([[99,  8,  5,  4],
       [ 8,  7,  3,  8],
       [ 4,  0,  2,  7]])

In [49]:
#コピー
x4 = np.random.randint(10, size=(3, 4))
x4

array([[4, 5, 0, 0],
       [3, 2, 4, 4],
       [7, 7, 8, 8]])

In [50]:
x4_sub_copy = x4[:2, :2].copy()
x4_sub_copy

array([[4, 5],
       [3, 2]])

In [51]:
x4_sub_copy[0,0] = 42
x4_sub_copy

array([[42,  5],
       [ 3,  2]])

In [52]:
x4

array([[4, 5, 0, 0],
       [3, 2, 4, 4],
       [7, 7, 8, 8]])

#PY14

In [53]:
#行列の形状変更
grid = np.arange(1, 10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
#grid.reshape((2, 5))

In [56]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [57]:
x.reshape((1, 3))

array([[1, 2, 3]])

In [58]:
x[np.newaxis]

array([[1, 2, 3]])

In [59]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [60]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [61]:
#行列の連結
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [62]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [63]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [64]:
z = [99, 999, 99]
np.concatenate([x, y, z])

array([  1,   2,   3,   4,   5,   6,  99, 999,  99])

In [65]:
#多次元
grid = np.array([[1, 2, 3], [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
grid.shape

(2, 3)

In [67]:
grid2 = np.concatenate([grid, grid], axis=0)
grid2

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [68]:
grid2.shape

(4, 3)

In [69]:
grid3 = np.concatenate([grid, grid], axis=1)
grid3

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [70]:
grid3.shape

(2, 6)

In [71]:
aaa = np.random.randint(10, size=(3, 4, 3))
aaa

array([[[3, 9, 7],
        [1, 3, 7],
        [5, 7, 2],
        [0, 4, 6]],

       [[0, 8, 0],
        [4, 7, 4],
        [4, 7, 2],
        [1, 1, 8]],

       [[2, 4, 5],
        [3, 6, 8],
        [4, 0, 2],
        [4, 7, 3]]])

In [72]:
np.concatenate([aaa, aaa], axis=2)

array([[[3, 9, 7, 3, 9, 7],
        [1, 3, 7, 1, 3, 7],
        [5, 7, 2, 5, 7, 2],
        [0, 4, 6, 0, 4, 6]],

       [[0, 8, 0, 0, 8, 0],
        [4, 7, 4, 4, 7, 4],
        [4, 7, 2, 4, 7, 2],
        [1, 1, 8, 1, 1, 8]],

       [[2, 4, 5, 2, 4, 5],
        [3, 6, 8, 3, 6, 8],
        [4, 0, 2, 4, 0, 2],
        [4, 7, 3, 4, 7, 3]]])

In [73]:
np.concatenate([aaa, aaa], axis=2).shape

(3, 4, 6)

In [74]:
np.concatenate([aaa, aaa], axis=1)

array([[[3, 9, 7],
        [1, 3, 7],
        [5, 7, 2],
        [0, 4, 6],
        [3, 9, 7],
        [1, 3, 7],
        [5, 7, 2],
        [0, 4, 6]],

       [[0, 8, 0],
        [4, 7, 4],
        [4, 7, 2],
        [1, 1, 8],
        [0, 8, 0],
        [4, 7, 4],
        [4, 7, 2],
        [1, 1, 8]],

       [[2, 4, 5],
        [3, 6, 8],
        [4, 0, 2],
        [4, 7, 3],
        [2, 4, 5],
        [3, 6, 8],
        [4, 0, 2],
        [4, 7, 3]]])

In [75]:
np.concatenate([aaa, aaa], axis=1).shape

(3, 8, 3)

In [76]:
np.concatenate([aaa, aaa], axis=0)

array([[[3, 9, 7],
        [1, 3, 7],
        [5, 7, 2],
        [0, 4, 6]],

       [[0, 8, 0],
        [4, 7, 4],
        [4, 7, 2],
        [1, 1, 8]],

       [[2, 4, 5],
        [3, 6, 8],
        [4, 0, 2],
        [4, 7, 3]],

       [[3, 9, 7],
        [1, 3, 7],
        [5, 7, 2],
        [0, 4, 6]],

       [[0, 8, 0],
        [4, 7, 4],
        [4, 7, 2],
        [1, 1, 8]],

       [[2, 4, 5],
        [3, 6, 8],
        [4, 0, 2],
        [4, 7, 3]]])

In [77]:
np.concatenate([aaa, aaa], axis=0)

array([[[3, 9, 7],
        [1, 3, 7],
        [5, 7, 2],
        [0, 4, 6]],

       [[0, 8, 0],
        [4, 7, 4],
        [4, 7, 2],
        [1, 1, 8]],

       [[2, 4, 5],
        [3, 6, 8],
        [4, 0, 2],
        [4, 7, 3]],

       [[3, 9, 7],
        [1, 3, 7],
        [5, 7, 2],
        [0, 4, 6]],

       [[0, 8, 0],
        [4, 7, 4],
        [4, 7, 2],
        [1, 1, 8]],

       [[2, 4, 5],
        [3, 6, 8],
        [4, 0, 2],
        [4, 7, 3]]])

#PY15

In [78]:
#行列の演算
x = np.arange(4)
x

array([0, 1, 2, 3])

In [79]:
x + 5

array([5, 6, 7, 8])

In [80]:
x - 5

array([-5, -4, -3, -2])

In [81]:
x * 2

array([0, 2, 4, 6])

In [82]:
x / 2

array([0. , 0.5, 1. , 1.5])

In [83]:
x // 2

array([0, 0, 1, 1])

In [84]:
x ** 3

array([ 0,  1,  8, 27])

In [85]:
x % 2

array([0, 1, 0, 1])

In [86]:
-(0.5 * x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [87]:
#集約
L = np.random.random(100)
L

array([0.03218477, 0.62119358, 0.40337016, 0.24561284, 0.49352679,
       0.01068551, 0.16917224, 0.23304831, 0.54752261, 0.13734837,
       0.27608191, 0.47475394, 0.98037167, 0.88434932, 0.14878894,
       0.71459332, 0.42505796, 0.06426444, 0.25401577, 0.35505254,
       0.24152555, 0.44061297, 0.20971994, 0.12492928, 0.8884406 ,
       0.17089062, 0.81587358, 0.42775528, 0.961889  , 0.69174866,
       0.81315773, 0.68107069, 0.08323074, 0.00850455, 0.22844154,
       0.08928088, 0.95862897, 0.22237466, 0.37551434, 0.21672979,
       0.70006143, 0.84425058, 0.81380199, 0.06868919, 0.65414994,
       0.29437848, 0.82442411, 0.59005742, 0.2056053 , 0.81054332,
       0.63047163, 0.90170825, 0.7817219 , 0.63594073, 0.48752177,
       0.41464286, 0.10628211, 0.42873916, 0.76433712, 0.39482733,
       0.55215754, 0.16254356, 0.0809078 , 0.67100556, 0.76087173,
       0.22274505, 0.63541188, 0.693959  , 0.1887375 , 0.89844793,
       0.68659958, 0.94517599, 0.12588419, 0.00204998, 0.58245

In [88]:
np.sum(L)

50.3557190243688

In [89]:
L.sum()

50.3557190243688

In [90]:
#最大・最小
np.min(L)

0.002049982017825247

In [91]:
L.min()

0.002049982017825247

In [92]:
np.max(L)

0.981986328864838

In [93]:
L.max()

0.981986328864838

In [94]:
#多次元配列の集約
M = np.random.random((3, 4))
M

array([[0.95646614, 0.77121439, 0.97276474, 0.13558054],
       [0.44696096, 0.51763517, 0.00325147, 0.48513111],
       [0.39417047, 0.1879786 , 0.74807593, 0.9370515 ]])

In [95]:
M.sum()

6.556281026597365

In [96]:
M.min(axis=0)

array([0.39417047, 0.1879786 , 0.00325147, 0.13558054])

In [97]:
M.max(axis=1)

array([0.97276474, 0.51763517, 0.9370515 ])

In [98]:
#平均・中央値・最頻値
np.mean(L)

0.5035571902436881

In [99]:
np.median(L)

0.5205247002618776

In [100]:
#マスク
x = np.random.randint(3, size= (30))
x

array([2, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 0, 1, 2, 2, 2, 2, 1, 2, 0, 0,
       2, 2, 0, 1, 2, 0, 0, 2])

In [101]:
x > 0

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True, False, False,  True,  True, False,  True,  True,
       False, False,  True])

In [102]:
x[x > 1]

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [103]:
np.mean(x[x > 0])

1.4782608695652173

#PY16

In [104]:
import numpy as np
import pandas as pd

In [105]:
#Series
data = pd.Series([0.25, 0.5, 0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [106]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [107]:
data[1]

0.5

In [108]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [109]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [110]:
data = pd.Series([0.25, 0.5, 0.75, 1], index=["a", "b", "c", "d"])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [111]:
data["c"]

0.75

In [112]:
data = pd.Series([0.25, 0.5, 0.75, 1], index=[1, 2, 3, 4])
data

1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [113]:
data[1]

0.25

In [114]:
population = pd.Series({
    "California" : 10000,
    "Texas" : 5000,
    "NewYork" : 3000
})


In [115]:
population["California"]

10000

In [116]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [117]:
pd.Series(5, index=[100, 200, 300])


100    5
200    5
300    5
dtype: int64

In [118]:
pd.Series({
    2: "a",
    1: "b",
    3: "c"
})

2    a
1    b
3    c
dtype: object

In [119]:
pd.Series({
    2 : "a",
    1 : "b",
    3 : "c"
}, index=[3,2])

3    c
2    a
dtype: object

In [120]:
#DataFrame
population = pd.Series({
    'California' : 38332521,
    'Texas' : 26448193,
    'NewYork': 19651127,
    'Florida' : 19552860,
    'Illinois' : 12882135
}) 

In [121]:
area = pd.Series({
    'California' : 423967,
    'Texas' : 695662,
    'NewYork': 141297,
    'Florida' : 170312,
    'Illinois' : 149995
}) 

In [122]:
population

California    38332521
Texas         26448193
NewYork       19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [123]:
area

California    423967
Texas         695662
NewYork       141297
Florida       170312
Illinois      149995
dtype: int64

In [124]:
states = pd.DataFrame({
    'population' : population,
    'area' : area
})

states

population    area
California    38332521  423967
Texas         26448193  695662
NewYork       19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [125]:
states.index

Index(['California', 'Texas', 'NewYork', 'Florida', 'Illinois'], dtype='object')

In [126]:
states.columns

Index(['population', 'area'], dtype='object')

In [127]:
states["area"]

California    423967
Texas         695662
NewYork       141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [128]:
data = pd.DataFrame([
                     [1.1, 1.3, 1.8, 1.6, 1.5],
                     [2.3, 2.1, 2.6, 2.8, 2.9]
])

data

0    1    2    3    4
0  1.1  1.3  1.8  1.6  1.5
1  2.3  2.1  2.6  2.8  2.9

In [129]:
data[0]

0    1.1
1    2.3
Name: 0, dtype: float64

In [130]:
data[0][1]

2.3

In [131]:
#pd.read_csv('sample_data/colifornia_housing_test.csv')

In [132]:
population = pd.Series({
    'California' : 38332521,
    'Texas' : 26448193,
    'NewYork': 19651127,
    'Florida' : 19552860,
    'Illinois' : 12882135
}) 


In [133]:
pd.DataFrame(population,columns=["population"])

population
California    38332521
Texas         26448193
NewYork       19651127
Florida       19552860
Illinois      12882135

In [134]:
pd.DataFrame([
              {'a': 1, 'b': 2},
              {'a': 3, 'b':4}
])

a  b
0  1  2
1  3  4

In [135]:
pd.DataFrame([
              {'a': 1, 'b': 2},
              {'a': 3, 'b':4, 'c': 4}
])

a  b    c
0  1  2  NaN
1  3  4  4.0

In [136]:
data = np.random.rand(3,2)
data

array([[0.75770658, 0.90406487],
       [0.48422727, 0.17086018],
       [0.3598789 , 0.12148828]])

In [137]:
pd.DataFrame(
    data,
    columns=["foo", "bar"],
    index = ["a", "b", "c"]
)

foo       bar
a  0.757707  0.904065
b  0.484227  0.170860
c  0.359879  0.121488

#PY17

In [138]:
data = pd.Series(
    [0.25, 0.5, 0.75, 1.0],
    index=["a", "b", "c", "d"]
)

data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [139]:
data["a"]

0.25

In [140]:
"b" in data

True

In [141]:
"e" in data

False

In [142]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [143]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [144]:
data["e"]  =1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [145]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [146]:
data[0:3]

a    0.25
b    0.50
c    0.75
dtype: float64

In [147]:
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [148]:
data = pd.Series(['a', 'b', 'c'], index=[1, 4, 6])
data[1]

'a'

In [149]:
data[4]

'b'

In [150]:
data[0:2]

1    a
4    b
dtype: object

In [151]:
data.loc[1:3]

1    a
dtype: object

In [152]:
data.iloc[1:3]

4    b
6    c
dtype: object

In [153]:
population

California    38332521
Texas         26448193
NewYork       19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [154]:
area

California    423967
Texas         695662
NewYork       141297
Florida       170312
Illinois      149995
dtype: int64

In [155]:
data = pd.DataFrame({
    'area': area,
    'pop': population
})

data

area       pop
California  423967  38332521
Texas       695662  26448193
NewYork     141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [156]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
NewYork     141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [157]:
data.area

California    423967
Texas         695662
NewYork       141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [158]:
data.pop

<bound method DataFrame.pop of               area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
NewYork     141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763>

In [159]:
data["area"]

California    423967
Texas         695662
NewYork       141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [160]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [161]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [162]:
data["area"]

California    423967
Texas         695662
NewYork       141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [163]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
NewYork     141297  19651127

In [164]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
NewYork     141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [165]:
data.loc[data["density"] > 100, ["pop", "density"] ]

pop     density
NewYork  19651127  139.076746
Florida  19552860  114.806121

In [166]:
data.T

California         Texas       NewYork       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [167]:
data = pd.DataFrame(
    np.random.randint(0, 10, (3,4)),
    columns=['A', 'B', 'C', 'D']
)

data

A  B  C  D
0  5  4  0  8
1  6  4  2  5
2  2  7  6  9

In [168]:
np.exp(data)

A            B           C            D
0  148.413159    54.598150    1.000000  2980.957987
1  403.428793    54.598150    7.389056   148.413159
2    7.389056  1096.633158  403.428793  8103.083928

In [169]:
np.sin(data* np.pi / 4)

A             B    C             D
0 -0.707107  1.224647e-16  0.0 -2.449294e-16
1 -1.000000  1.224647e-16  1.0 -7.071068e-01
2  1.000000 -7.071068e-01 -1.0  7.071068e-01

In [170]:
data['sinA'] = np.sin(data['A'])
data

A  B  C  D      sinA
0  5  4  0  8 -0.958924
1  6  4  2  5 -0.279415
2  2  7  6  9  0.909297

#PY18

In [171]:
#欠損値
data = pd.DataFrame({
    'col1' : [1, 2, None, np.nan],
    'col2' : [1.2, 2.3, None, np.nan],
    'col3' : ['aaa', 'bbb', None, np.nan],    
})

data

col1  col2  col3
0   1.0   1.2   aaa
1   2.0   2.3   bbb
2   NaN   NaN  None
3   NaN   NaN   NaN

In [172]:
data.isna()

col1   col2   col3
0  False  False  False
1  False  False  False
2   True   True   True
3   True   True   True

In [173]:
data.notna()

col1   col2   col3
0   True   True   True
1   True   True   True
2  False  False  False
3  False  False  False

In [174]:
pd.notna(data)

col1   col2   col3
0   True   True   True
1   True   True   True
2  False  False  False
3  False  False  False

In [175]:
data.dropna()

col1  col2 col3
0   1.0   1.2  aaa
1   2.0   2.3  bbb

In [176]:
aaa = data.dropna()
aaa.loc[0, 'col1'] = 5
aaa

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)


col1  col2 col3
0   5.0   1.2  aaa
1   2.0   2.3  bbb

In [177]:
data

col1  col2  col3
0   1.0   1.2   aaa
1   2.0   2.3   bbb
2   NaN   NaN  None
3   NaN   NaN   NaN

In [178]:
df = pd.DataFrame(
    [[1, np.nan, 2],
    [2, 4, 5],
    [np.nan, 4, 6]]
)

df

0    1  2
0  1.0  NaN  2
1  2.0  4.0  5
2  NaN  4.0  6

In [179]:
df.dropna()

0    1  2
1  2.0  4.0  5

In [180]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [181]:
df[3] = np.nan

In [182]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  4.0  5 NaN
2  NaN  4.0  6 NaN

In [183]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  4.0  5
2  NaN  4.0  6

In [184]:
df.dropna(axis='columns', thresh=2)

0    1  2
0  1.0  NaN  2
1  2.0  4.0  5
2  NaN  4.0  6

In [185]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('absde'))
data

a    1.0
b    NaN
s    2.0
d    NaN
e    3.0
dtype: float64

In [186]:
data.fillna(0
            )

a    1.0
b    0.0
s    2.0
d    0.0
e    3.0
dtype: float64

In [187]:
data.fillna(method='ffill')

a    1.0
b    1.0
s    2.0
d    2.0
e    3.0
dtype: float64

In [188]:
data.fillna(method='bfill')

a    1.0
b    2.0
s    2.0
d    3.0
e    3.0
dtype: float64

In [189]:
df = pd.DataFrame(
    [[1, np.nan, 2],
     [2, 3, 5],
     [np.nan, 4, 6]]
)
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [190]:
df.fillna(method='ffill', axis=1)

0    1    2
0  1.0  1.0  2.0
1  2.0  3.0  5.0
2  NaN  4.0  6.0

In [191]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])

In [192]:
ser1

1    A
2    B
3    C
dtype: object

In [193]:
ser2

4    D
5    E
6    F
dtype: object

In [194]:
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

#PY19

In [195]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [196]:
def make_d(cols, ind):
  return pd.DataFrame({
      c: [str(c) + str(i) for i in ind]
       for c in cols}, ind
  )

In [197]:
df1 = make_d('AB', [1,2])
df1

A   B
1  A1  B1
2  A2  B2

In [198]:
df2 = make_d('AB', [3, 4])
df2

A   B
3  A3  B3
4  A4  B4

In [199]:
pd.concat([df1, df2])


A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [200]:
df1.append(df2)

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [201]:
df3 = make_d('AB', [0, 1])
df3

A   B
0  A0  B0
1  A1  B1

In [202]:
df4 = make_d('CD', [0, 1])
df4

C   D
0  C0  D0
1  C1  D1

In [203]:
pd.concat([df3, df4], axis=1)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

In [204]:
df5 = make_d('ABC', [1, 2])
df5

A   B   C
1  A1  B1  C1
2  A2  B2  C2

In [205]:
df6 = make_d('BCD', [3, 4])
df6

B   C   D
3  B3  C3  D3
4  B4  C4  D4

In [206]:
pd.concat([df5, df6])

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [207]:
pd.concat([df5, df6], join='inner')

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [208]:
df1 = pd.DataFrame({
    'employee' : ['Bob', 'Jake', 'Lisa', 'Sue'],
    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']
})

df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [209]:
df2 = pd.DataFrame({
    'employee' : ['Lisa', 'Bob', 'Jake', 'Sue'],
    'hier_date': [2004, 2008, 2012, 2014]
})

df2

employee  hier_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [210]:
df3 = pd.merge(df1, df2)
df3

employee        group  hier_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [211]:
df4 = pd.DataFrame({
    'group': ['Accounting', 'Engineering', 'HR'],
    'supervisor': ['Carly', 'Guide', 'Steve'] 
})

df4

group supervisor
0   Accounting      Carly
1  Engineering      Guide
2           HR      Steve

In [212]:
pd.merge(df3, df4)

employee        group  hier_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guide
2     Lisa  Engineering       2004      Guide
3      Sue           HR       2014      Steve

In [213]:
df5 = pd.DataFrame({
    'group' : ['Accounting', 'Accounting', 'Engineering', 'Engineering', 'HR', 'HR'],
    'skills': ['math', 'spreadsheets', 'coding', 'linux', 'spreadsheets', 'organaization']
})
df5

group         skills
0   Accounting           math
1   Accounting   spreadsheets
2  Engineering         coding
3  Engineering          linux
4           HR   spreadsheets
5           HR  organaization

In [214]:
pd.merge(df1, df5)

employee        group         skills
0      Bob   Accounting           math
1      Bob   Accounting   spreadsheets
2     Jake  Engineering         coding
3     Jake  Engineering          linux
4     Lisa  Engineering         coding
5     Lisa  Engineering          linux
6      Sue           HR   spreadsheets
7      Sue           HR  organaization

In [215]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [216]:
df2

employee  hier_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [217]:
pd.merge(df1, df2, on='employee')

employee        group  hier_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [218]:
df6 = pd.DataFrame({
    'name' : ['Peter', 'Paul', 'Mary'],
    'food' : ['fish', 'beans', 'bread']},
    columns=['name', 'food']
)

df6

name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

In [219]:
df7 = pd.DataFrame({
    'name' : ['Mary', 'Joseph'],
    'drink' : ['beer', 'wine', ]},
    columns=['name', 'drink']
)

df7

name drink
0    Mary  beer
1  Joseph  wine

In [220]:
pd.merge(df6, df7)

name   food drink
0  Mary  bread  beer

In [221]:
pd.merge(df6, df7, how = 'inner')

name   food drink
0  Mary  bread  beer

In [222]:
pd.merge(df6, df7, how = 'outer')

name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  beer
3  Joseph    NaN  wine

In [223]:
pd.merge(df6, df7, how = 'left')

name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  beer

In [224]:
#集約
ser = pd.Series(np.random.rand(5))
ser

0    0.559617
1    0.449181
2    0.854161
3    0.336660
4    0.529174
dtype: float64

In [225]:
ser.sum()

2.72879208156401

In [226]:
ser.mean()

0.545758416312802

In [227]:
df = pd.DataFrame({
    'A' : np.random.rand(5),
    'B' : np.random.rand(5),
})

df

A         B
0  0.221679  0.589723
1  0.533939  0.760671
2  0.892464  0.436334
3  0.302432  0.983789
4  0.229229  0.988805

In [228]:
df.mean()

A    0.435949
B    0.751865
dtype: float64

In [229]:
df.describe()

A         B
count  5.000000  5.000000
mean   0.435949  0.751865
std    0.284816  0.242825
min    0.221679  0.436334
25%    0.229229  0.589723
50%    0.302432  0.760671
75%    0.533939  0.983789
max    0.892464  0.988805

In [230]:
#グループ化
df = pd.DataFrame({
    'key': ['A', 'B', 'C', 'A', 'B', 'C'],
    'data': range(6)
}, columns=['key', 'data'])

df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [231]:
df.groupby('key')

In [232]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7

In [233]:
df.groupby('key').aggregate([min, np.median, max])

data           
     min median max
key                
A      0    1.5   3
B      1    2.5   4
C      2    3.5   5

#PY20

コードなし