<a href="https://colab.research.google.com/github/Mori-Don/RabbitChallenge/blob/main/RabbitChallenge_PythonKoza_11_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # PY11

In [1]:
#numpy
import numpy as np

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [6]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [7]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
np.random.random((3, 4))

array([[0.04091982, 0.41195761, 0.23331617, 0.57931527],
       [0.51940047, 0.64672175, 0.99071677, 0.43300801],
       [0.04578515, 0.57226155, 0.10113625, 0.71840924]])

In [9]:
np.random.normal(0, 1, (3,3))

array([[-0.18582086,  0.16387113,  0.06560156],
       [-0.4543301 ,  1.655537  ,  2.11505459],
       [ 0.04851594, -0.53811867,  1.30793018]])

In [10]:
np.random.randint(0, 255, (100,150))

array([[210, 137, 231, ..., 142,   9,  24],
       [ 55,  48, 188, ..., 186, 246,  50],
       [239, 171, 146, ..., 147, 101, 210],
       ...,
       [182, 171, 161, ...,  32, 228,  75],
       [191, 146, 118, ...,  40, 201, 167],
       [ 80,  96,  11, ...,  18, 182, 183]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#PY12

In [12]:
from sklearn import datasets

mnist = datasets.load_digits()

In [13]:
mnist["images"]

array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  0.,  0.],
        [ 0.,  0.,  8., ..., 16.,  0.,  0.],
        ...,
        [ 0.,  9., 16., ...,  0.,  0.,  0.],
        [ 0.,  3., 13., ..., 11.,  5.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

       ...,

       [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ...,  2.,  1.,  0.],
        [ 0.,  0., 16., ..., 16.,  5.,  0.

In [14]:
mnist["target"]

array([0, 1, 2, ..., 8, 9, 8])

In [15]:
mnist["images"].ndim

3

In [16]:
mnist["target"].ndim

1

In [17]:
mnist["images"].shape

(1797, 8, 8)

In [18]:
mnist["target"].shape

(1797,)

In [19]:
x1 = np.zeros(6, dtype=np.float16)
x2 = np.zeros((3, 4), dtype=np.uint8)
x3 = np.zeros((3, 4, 5), dtype=np.float32)

In [20]:
x1

array([0., 0., 0., 0., 0., 0.], dtype=float16)

In [21]:
x2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [22]:
x3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)

In [23]:
x1.ndim

1

In [24]:
x2.ndim

2

In [25]:
x3.ndim

3

In [26]:
x1.shape

(6,)

In [27]:
x2.shape

(3, 4)

In [28]:
x3.shape

(3, 4, 5)

In [29]:
x1.size

6

In [30]:
x2.size

12

In [31]:
x3.size

60

In [32]:
x1.dtype

dtype('float16')

In [33]:
x2.dtype

dtype('uint8')

In [34]:
x3.dtype

dtype('float32')

#PY13

In [35]:
#一次元
x1 = np.random.randint(10, size=(6))
x1

array([2, 5, 4, 3, 4, 0])

In [36]:
x1[0]

2

In [37]:
x1[3]

3

In [38]:
x1[-1]

0

In [39]:
x1[-4]

4

In [41]:
x1[2] = 8
x1

array([2, 5, 8, 3, 4, 0])

In [49]:
#多次元
x2 = np.random.randint(10, size=(3,4))
x2

array([[8, 7, 3, 9],
       [7, 5, 1, 9],
       [9, 5, 1, 6]])

In [50]:
x2[0, 0]

8

In [51]:
x2[2, -1]

6

In [52]:
x2[0, 0] = 12
x2

array([[12,  7,  3,  9],
       [ 7,  5,  1,  9],
       [ 9,  5,  1,  6]])

In [53]:
#ビュー
x3 = np.random.randint(10, size=(3,4))
x3

array([[6, 4, 3, 6],
       [1, 1, 0, 5],
       [6, 4, 1, 8]])

In [55]:
x3_sub = x3[:2, :2]
x3_sub

array([[6, 4],
       [1, 1]])

In [56]:
x3_sub[0, 0] = 99
x3_sub

array([[99,  4],
       [ 1,  1]])

In [57]:
x3

array([[99,  4,  3,  6],
       [ 1,  1,  0,  5],
       [ 6,  4,  1,  8]])

In [58]:
#コピー
x4 = np.random.randint(10, size=(3, 4))
x4

array([[4, 8, 8, 8],
       [7, 2, 0, 3],
       [8, 4, 3, 6]])

In [59]:
x4_sub_copy = x4[:2, :2].copy()
x4_sub_copy

array([[4, 8],
       [7, 2]])

In [60]:
x4_sub_copy[0,0] = 42
x4_sub_copy

array([[42,  8],
       [ 7,  2]])

In [61]:
x4

array([[4, 8, 8, 8],
       [7, 2, 0, 3],
       [8, 4, 3, 6]])

#PY14

In [63]:
#行列の形状変更
grid = np.arange(1, 10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
#grid.reshape((2, 5))

In [67]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [68]:
x.reshape((1, 3))

array([[1, 2, 3]])

In [69]:
x[np.newaxis]

array([[1, 2, 3]])

In [71]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [72]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [73]:
#行列の連結
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [74]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [75]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [77]:
z = [99, 999, 99]
np.concatenate([x, y, z])

array([  1,   2,   3,   4,   5,   6,  99, 999,  99])

In [78]:
#多次元
grid = np.array([[1, 2, 3], [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
grid.shape

(2, 3)

In [82]:
grid2 = np.concatenate([grid, grid], axis=0)
grid2

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [83]:
grid2.shape

(4, 3)

In [86]:
grid3 = np.concatenate([grid, grid], axis=1)
grid3

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [88]:
grid3.shape

(2, 6)

In [90]:
aaa = np.random.randint(10, size=(3, 4, 3))
aaa

array([[[6, 3, 6],
        [7, 7, 1],
        [2, 4, 8],
        [2, 8, 1]],

       [[3, 2, 2],
        [6, 8, 2],
        [1, 6, 4],
        [3, 6, 1]],

       [[1, 1, 2],
        [5, 4, 7],
        [3, 4, 1],
        [1, 7, 7]]])

In [91]:
np.concatenate([aaa, aaa], axis=2)

array([[[6, 3, 6, 6, 3, 6],
        [7, 7, 1, 7, 7, 1],
        [2, 4, 8, 2, 4, 8],
        [2, 8, 1, 2, 8, 1]],

       [[3, 2, 2, 3, 2, 2],
        [6, 8, 2, 6, 8, 2],
        [1, 6, 4, 1, 6, 4],
        [3, 6, 1, 3, 6, 1]],

       [[1, 1, 2, 1, 1, 2],
        [5, 4, 7, 5, 4, 7],
        [3, 4, 1, 3, 4, 1],
        [1, 7, 7, 1, 7, 7]]])

In [92]:
np.concatenate([aaa, aaa], axis=2).shape

(3, 4, 6)

In [93]:
np.concatenate([aaa, aaa], axis=1)

array([[[6, 3, 6],
        [7, 7, 1],
        [2, 4, 8],
        [2, 8, 1],
        [6, 3, 6],
        [7, 7, 1],
        [2, 4, 8],
        [2, 8, 1]],

       [[3, 2, 2],
        [6, 8, 2],
        [1, 6, 4],
        [3, 6, 1],
        [3, 2, 2],
        [6, 8, 2],
        [1, 6, 4],
        [3, 6, 1]],

       [[1, 1, 2],
        [5, 4, 7],
        [3, 4, 1],
        [1, 7, 7],
        [1, 1, 2],
        [5, 4, 7],
        [3, 4, 1],
        [1, 7, 7]]])

In [94]:
np.concatenate([aaa, aaa], axis=1).shape

(3, 8, 3)

In [95]:
np.concatenate([aaa, aaa], axis=0)

array([[[6, 3, 6],
        [7, 7, 1],
        [2, 4, 8],
        [2, 8, 1]],

       [[3, 2, 2],
        [6, 8, 2],
        [1, 6, 4],
        [3, 6, 1]],

       [[1, 1, 2],
        [5, 4, 7],
        [3, 4, 1],
        [1, 7, 7]],

       [[6, 3, 6],
        [7, 7, 1],
        [2, 4, 8],
        [2, 8, 1]],

       [[3, 2, 2],
        [6, 8, 2],
        [1, 6, 4],
        [3, 6, 1]],

       [[1, 1, 2],
        [5, 4, 7],
        [3, 4, 1],
        [1, 7, 7]]])

In [96]:
np.concatenate([aaa, aaa], axis=0)

array([[[6, 3, 6],
        [7, 7, 1],
        [2, 4, 8],
        [2, 8, 1]],

       [[3, 2, 2],
        [6, 8, 2],
        [1, 6, 4],
        [3, 6, 1]],

       [[1, 1, 2],
        [5, 4, 7],
        [3, 4, 1],
        [1, 7, 7]],

       [[6, 3, 6],
        [7, 7, 1],
        [2, 4, 8],
        [2, 8, 1]],

       [[3, 2, 2],
        [6, 8, 2],
        [1, 6, 4],
        [3, 6, 1]],

       [[1, 1, 2],
        [5, 4, 7],
        [3, 4, 1],
        [1, 7, 7]]])

#PY15

In [97]:
#行列の演算
x = np.arange(4)
x

array([0, 1, 2, 3])

In [98]:
x + 5

array([5, 6, 7, 8])

In [104]:
x - 5

array([-5, -4, -3, -2])

In [103]:
x * 2

array([0, 2, 4, 6])

In [102]:
x / 2

array([0. , 0.5, 1. , 1.5])

In [105]:
x // 2

array([0, 0, 1, 1])

In [106]:
x ** 3

array([ 0,  1,  8, 27])

In [107]:
x % 2

array([0, 1, 0, 1])

In [108]:
-(0.5 * x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [109]:
#集約
L = np.random.random(100)
L

array([0.31507728, 0.90665381, 0.04622124, 0.76945973, 0.88938255,
       0.20517054, 0.81842869, 0.61939719, 0.07137406, 0.75845042,
       0.8284207 , 0.97889645, 0.51230107, 0.85941159, 0.1698842 ,
       0.0526291 , 0.69899347, 0.65381023, 0.31672915, 0.16589356,
       0.7481821 , 0.07943213, 0.79876274, 0.50473428, 0.67436412,
       0.07120463, 0.05403119, 0.06269712, 0.26039103, 0.37681094,
       0.75739611, 0.58891498, 0.76481093, 0.34174543, 0.98647209,
       0.18289801, 0.14296765, 0.1597262 , 0.96141881, 0.33215012,
       0.85519886, 0.36681402, 0.99898913, 0.09675592, 0.02994859,
       0.02924963, 0.29612036, 0.70397322, 0.49865052, 0.58017413,
       0.55607428, 0.94455003, 0.12535052, 0.98380533, 0.56420359,
       0.42140223, 0.77727464, 0.46870314, 0.85067074, 0.28262895,
       0.95798603, 0.21750642, 0.1658656 , 0.35132673, 0.68272511,
       0.18883095, 0.7562868 , 0.39998475, 0.71820738, 0.29500251,
       0.04494461, 0.79353601, 0.88088295, 0.46889423, 0.09689

In [110]:
np.sum(L)

51.304142409475425

In [111]:
L.sum()

51.304142409475425

In [112]:
#最大・最小
np.min(L)

0.008593699533954502

In [113]:
L.min()

0.008593699533954502

In [114]:
np.max(L)

0.9989891282644452

In [115]:
L.max()

0.9989891282644452

In [116]:
#多次元配列の集約
M = np.random.random((3, 4))
M

array([[0.53262855, 0.40269204, 0.73642165, 0.48778152],
       [0.62248229, 0.57202275, 0.05157199, 0.47148194],
       [0.97803616, 0.04505754, 0.62861127, 0.53472678]])

In [117]:
M.sum()

6.06351446799867

In [120]:
M.min(axis=0)

array([0.53262855, 0.04505754, 0.05157199, 0.47148194])

In [121]:
M.max(axis=1)

array([0.73642165, 0.62248229, 0.97803616])

In [122]:
#平均・中央値・最頻値
np.mean(L)

0.5130414240947543

In [123]:
np.median(L)

0.5134747767465404

In [124]:
#マスク
x = np.random.randint(3, size= (30))
x

array([0, 2, 1, 0, 0, 1, 0, 1, 1, 2, 2, 0, 2, 0, 1, 1, 0, 1, 2, 1, 0, 1,
       0, 2, 0, 1, 1, 2, 2, 0])

In [125]:
x > 0

array([False,  True,  True, False, False,  True, False,  True,  True,
        True,  True, False,  True, False,  True,  True, False,  True,
        True,  True, False,  True, False,  True, False,  True,  True,
        True,  True, False])

In [126]:
x[x > 1]

array([2, 2, 2, 2, 2, 2, 2, 2])

In [127]:
np.mean(x[x > 0])

1.4210526315789473

#PY16