 # PY11

In [1]:
#numpy
import numpy as np

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [8]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
np.random.random((3, 4))

array([[0.12129581, 0.71703924, 0.68492788, 0.72004066],
       [0.84632498, 0.98256485, 0.1067552 , 0.80974421],
       [0.27140202, 0.74419271, 0.85320449, 0.32927469]])

In [10]:
np.random.normal(0, 1, (3,3))

array([[ 1.14818039,  0.05358002, -0.78789237],
       [ 1.26506697,  0.4749556 ,  0.06751489],
       [-1.04465278, -1.20825263, -2.38473114]])

In [13]:
np.random.randint(0, 255, (100,150))

array([[ 22,  20,  71, ...,  98,  97,  58],
       [243, 219,  38, ..., 216, 108, 132],
       [197,  98,  82, ..., 192,  33, 239],
       ...,
       [233,  71,  39, ...,  29, 127, 233],
       [126, 208, 158, ..., 173, 221,   8],
       [ 93, 132,   9, ..., 241, 120, 236]])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#PY12

In [15]:
from sklearn import datasets

mnist = datasets.load_digits()

In [18]:
mnist["images"]

array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  0.,  0.],
        [ 0.,  0.,  8., ..., 16.,  0.,  0.],
        ...,
        [ 0.,  9., 16., ...,  0.,  0.,  0.],
        [ 0.,  3., 13., ..., 11.,  5.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

       ...,

       [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ...,  2.,  1.,  0.],
        [ 0.,  0., 16., ..., 16.,  5.,  0.

In [19]:
mnist["target"]

array([0, 1, 2, ..., 8, 9, 8])

In [20]:
mnist["images"].ndim

3

In [22]:
mnist["target"].ndim

1

In [24]:
mnist["images"].shape

(1797, 8, 8)

In [25]:
mnist["target"].shape

(1797,)

In [27]:
x1 = np.zeros(6, dtype=np.float16)
x2 = np.zeros((3, 4), dtype=np.uint8)
x3 = np.zeros((3, 4, 5), dtype=np.float32)

In [28]:
x1

array([0., 0., 0., 0., 0., 0.], dtype=float16)

In [29]:
x2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [30]:
x3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)

In [32]:
x1.ndim

1

In [33]:
x2.ndim

2

In [34]:
x3.ndim

3

In [35]:
x1.shape

(6,)

In [36]:
x2.shape

(3, 4)

In [38]:
x3.shape

(3, 4, 5)

In [39]:
x1.size

6

In [40]:
x2.size

12

In [41]:
x3.size

60

In [42]:
x1.dtype

dtype('float16')

In [43]:
x2.dtype

dtype('uint8')

In [44]:
x3.dtype

dtype('float32')

#PY13